tek1 = input("Mani sauc: ")
tek2 = input("Man patīk: ")
tek3 = input("Es mācos: ")
tek4 = input("Mana mīļākā stunda ir: ")
tek5 = input("Es nākotnē strādāšu par: ")
print(f"Mani sauc {tek1}.")
print(f"Man patīk {tek2}.")
print(f"Es mācos {tek3}.")
print(f"Mana mīļākā stunda ir {tek4}.")
print(f"Es nākotnē strādāšu par {tek5}.")
